### ISSUE TITLE
Comparing learned representations

### ISSUE THREAD

**Issue by kalyani7195** [krishnap25/mauve#12]
I was wondering if mauve can be applied in a slightly different setting. So if I understand correctly -- Given two text distributions t1 and t2, mauve first computes fixed dimensional representations using a pretrained model like GPT-2. Let's say the features are: t1-(100, 1024), t2- (150, 1024). Then a common dataset d1 (250, 1024) is created and clustered using K-means. The cluster assignments are then used to compute normalized histograms which are then used to plot the divergence curve and then quantify the gap using AUC.

So my question is can we use mauve to compare the representations and quantify the information gap between the representations? Here we do not have two datasets from different data distributions, but two representations of the same data distribution -- for e.g.  8 and 16 dimensions. I am guessing we cannot use mauve directly here because we cannot combine them to form d1 (as the dimensions are different) and then cluster them. right? Do you have any suggestions on how it can be done by modifying mauve?
Thanks,
Kalyani

**Comment by krishnap25** [comment]
Hi @kalyani7195, 

MAUVE requires both distributions in a common embedding space, so you cannot directly compare two different embeddings. But this is a super interesting question, and it should be possible to make this comparison indirectly. 

You could try designing two distributions P and Q that are different in the 16-dimensional embedding space but very similar in the 8-dimensional space. Of course, depending on your embeddings, this might be a very hard problem, but I have seem some examples in the text setting where this seems possible. 

Does this make sense?

Best, 
Krishna

**Comment by kalyani7195** [comment]
Yes, that makes sense. Thank you!
