### ISSUE TITLE
Question about the Spearman rank correlation

### ISSUE THREAD

**Issue by bigbrother001** [krishnap25/mauve#6]
Thanks for great paper! However I'm have a little bit confusion about the Spearman rank correlation in § 4.3 and Appendix E. 
While calculating Spearman rank correlation between MAUVE and human, do you mean to use eight figures from MAUVE and other eight figures from Bradley-Terry model?

**Comment by krishnap25** [comment]
Hi @bigbrother001, 

That is correct, we use 8 values of MAUVE and the corresponding 8 values from the Bradley-Terry model from Table 6 and Table 13 of Appendix E. 

Here is some sample code, hope this helps. 
```python
df = your_function_to_combine_experimental_results_into_dataframe() 
df
```
|                                        |   BT/Human-like |   BT/Interesting |   BT/Sensible |    MAUVE |
|:---------------------------------------|----------------:|-----------------:|--------------:|---------:|
| ('gpt2-xl', 'nucleus_0.95')    |        15.6638  |        23.0456   |      31.8877  | 0.939627 |
| ('gpt2-large', 'nucleus_0.95') |        12.5526  |         6.78507  |       8.78143 | 0.935884 |
| ('gpt2-xl', 'sampling')        |         8.9663  |         9.52902  |       7.7525  | 0.881567 |
| ('gpt2-medium', 'nucleus_0.9') |        -3.42942 |       -12.8236   |      -7.29327 | 0.914602 |
| ('gpt2-large', 'sampling')     |        -6.93485 |        -1.53243  |      -7.10611 | 0.844997 |
| ('gpt2', 'nucleus_0.9')        |       -15.7833  |        -0.696617 |      -7.44177 | 0.877525 |
| ('gpt2', 'sampling')           |       -27.5176  |       -15.4873   |     -37.8055  | 0.589043 |
| ('gpt2-medium', 'sampling')    |       -30.7686  |       -34.3229   |     -32.0043  | 0.372786 |


```python
from scipy.stats import spearmanr
print(spearmanr(df["MAUVE"], df["BT/Human-like"]))
# SpearmanrResult(correlation=0.9523809523809524, pvalue=0.00026040002438725105)
```

**Comment by bigbrother001** [comment]
Thank you!
