### ISSUE TITLE
Mabye incorrect calculation in one small line

### ISSUE THREAD

**Issue by stavyos** [krishnap25/mauve#7]
Hi,
First, thanks for the awesome paper.

https://github.com/krishnap25/mauve/blob/20613eecd7b084281ed4df9bfeee67d66cbfe5ee/src/mauve/compute_mauve.py#L249-L263

I think there is an issue at line 258, where the closing parentheses is placed.
Mabye it's supposed to be like this:
```python
elif abs(p1 - q1) > 1e-8:
```

Tried to find this in the paper and in the fronter intergral but nothing jumped into my eyes.

Thanks

**Comment by krishnap25** [comment]
Hi @stav95, 

Your proposal and the [actual line of code](https://github.com/krishnap25/mauve/blob/main/src/mauve/compute_mauve.py#L258) look identical to me. Could you double-check? Perhaps we have already fixed the issue your refer to and you're looking at an outdated version of repo. 

For the exact formula we used, please see Appendix B of [the frontier integral paper](https://arxiv.org/pdf/2106.07898.pdf). 

As p1 - q1 gets smaller, the term t2 gets smaller (and is 0 in the limit that p1 = q1). Unfortunately, the term is also poorly conditioned, and the numerical error is bound to grow much larger as p1 - q1 gets smaller. We have this guard in place to avoid that from happening. 

Hope this helps. 
Krishna

**Comment by stavyos** [comment]
Hi @krishnap25,

That's very weird, my mauve version the latest version:
![image](https://user-images.githubusercontent.com/46630739/158805489-fb02456a-9750-4f09-8774-de4d1fe6122a.png)

And take a look at the file in my IDE (PyCharm)
![image](https://user-images.githubusercontent.com/46630739/158800666-a9e01e90-0c35-4b36-8b90-418823c7eb96.png)

-----
**Update:**

I looked at the commits on this file and you already fixed this isuue in the past but still on https://pypi.org/project/mauve-text/ is not updated.

The commit: https://github.com/krishnap25/mauve/commit/b3c01d5b0f3be85a997b1171b3f2efa3ba16280b
Because the repo is small I Just installed it manually

Thanks,
Stav

**Comment by krishnap25** [comment]
Good point. We haven't updated the pip package yet since this update was
merged. We should update it within the next week or so.

Thank you for pointing this out!
