### ISSUE TITLE
How can I accelerate the featurizing of MAUVE score

### ISSUE THREAD

**Issue by Jxu-Thu** [krishnap25/mauve#8]
I try to direct leverage MAUVE API such as 

out = mauve.compute_mauve(p_text=p_text, q_text=q_text, device_id=0, max_text_length=256, verbose=False).

I find that the GPU memory usage is quite low. How could I accelerate the calculation (featuring of sequence) of MAUVE score. 

I note there is a hyper-parameter ''batch_size''. Could I tune the hyperparameter? Do different values cause different results? What is the default value of the ''batchsize''?

**Comment by Jxu-Thu** [comment]
It seems that there is no batchsize hyper-parameter in "pip" version

**Comment by krishnap25** [comment]
Hi @Jxu-Thu, 

The default value of batch size is 1. You want to choose a batch size large enough to saturate your GPU memory. The best way (that I know of) to find the right batch size is to do a binary search between 1 and something large like 1024. 

Using any batch size leads to the same features up to numerical error (~1e-5 in relative error), so the final MAUVE score is effectively the same. 

For example, with `featurize_model_name = "gpt2-large"` and `max_len=1024` on  a Nvidia 1080 Ti GPU (~12G memory), a batch size of 8 works. If you have 24G memory on your GPU, double this batch size will work. Here is a way to automate this:
```
import torch
def get_default_batch_size(device):
    twelve_gigs = 11719409664
    default_batch_size = 8  # works for 12G memory on GPU
    memory = torch.cuda.get_device_properties(device).total_memory
    return max(1, int(memory / twelve_gigs * default_batch_size))
```

As for the pip package, we will update it soon -- hopefully this week (we only periodically update the pip package once enough updates have been collected). Please pull from github and install locally in the meanwhile (instructions [here](https://krishnap25.github.io/mauve/#installation)). 

Best, 
Krishna

**Comment by Jxu-Thu** [comment]
Thanks for your answer! I am looking forward to the new pip package supporting batchsize feature.

**Comment by krishnap25** [comment]
The version with minibatching is now available via pip. Thank you for your patience!
