### ISSUE TITLE
WARNING clustering 13104 points to 655 centroids: please provide at least 25545 training points

### ISSUE THREAD

**Issue by ivnle** [krishnap25/mauve#9]
I received this warning when running MAUVE with basically default settings.
`mauve_out = mauve.compute_mauve(p_text=p_text, q_text=q_text, verbose=False, device_id=0)`
`WARNING clustering 13104 points to 655 centroids: please provide at least 25545 training points`

I've provided ~6,500 generations each for `p_text ` and `q_text` which is more than the 5,000 used in the paper. Is this warning safe to ignore? The generations are fairly short compared to those in the paper (~20 BPE tokens).

**Comment by krishnap25** [comment]
Hi @ivnle, 

I wouldn't worry about this warning. See [here](https://github.com/krishnap25/mauve/issues/4) for details. 

I would, however, be concerned about the length of the generations. For such short generations (20 BPE tokens ~ 1-2 sentences), there might not be enough signal. At this length, most reasonable models and most decoding algorithms can produce decent text (this also depends on the task).
